
runner:
  total_steps: 2500 # 40000
  gradient_clipping: 1
  gradient_accumulate_steps: 4

  log_step: 85
  eval_step: 85
  save_step: 85
  max_keep: 1
  eval_dataloaders: 
    - dev
    - test
  
optimizer:
  name: TorchOptim
  torch_optim_name: Adam
  lr: 1.0e-4 #1.0e-2

# # comment the whole scheduler config block to disable learning rate scheduling
# scheduler:
#   name: linear_schedule_with_warmup
#   num_warmup_steps: 5000

downstream_expert: 
  datarc:
    file_path: /path/to/bu_radio
    meta_data: /path/to/s3prl_tobi/bu_radio_dataset/metadata/splits.tsv
    sr: 16000
    num_workers: 8
    train_batch_size: 16
    eval_batch_size: 1
    # max_timestep: 128000
    return_glottal: True
    window_size: 0.2
    labels_mode: 0123v4
    glottal_kwargs:
      return_glottal: True

  modelrc:
    projector_dim: 256
    select: UtteranceLevelBeforeAfter
    UtteranceLevelBeforeAfter:
      pooling: AttentivePooling
    feature_rate: 62.5
